# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("1pgifm6esdu2xf8j10vuoyu8cvi88uua.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {\n"
                                 "    background-color: #2E2B3F;\n"
                                 "    border: none;\n"
                                 "}\n"
                                 "QMenuBar {\n"
                                 "    background-color: #2E2B3F; /* Цвет фона для верхней панели меню */\n"
                                 "    color: white; /* Цвет текста */\n"
                                 "    border: none; /* Убирает рамку, если есть */\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget {\n"
                                         "    background-color: #2E2B3F; /* Цвет фона */\n"
                                         "    border: none;\n"
                                         "}\n"
                                         "")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget {\n"
                                     "    background-color: #2E2B3F; /* Цвет фона для всего виджета */\n"
                                     "    border: none;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab {\n"
                                     "    background :#7961F1; /* Цвет фона вкладки */\n"
                                     "    color: #333333; /* Цвет текста */\n"
                                     "    padding: 10px; /* Отступы */\n"
                                     "    border-bottom: none; /* Убираем нижнюю рамку для активной вкладки */\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:selected {\n"
                                     "    background: #0090B3; /* Цвет фона для выбранной вкладки */\n"
                                     "    color: white; /* Цвет текста для выбранной вкладки */\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:hover {\n"
                                     "    background-color: #e67e22; /* Цвет фона при наведении */\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:!selected {\n"
                                     "    margin-left: 0px; /* Отступ между вкладками */\n"
                                     "}\n"
                                     "\n"
                                     "QTabWidget::pane {\n"
                                     "    border: none; /* Убирает рамку вокруг вкладок */\n"
                                     "}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tab.setFont(font)
        self.tab.setStyleSheet("QWidget {\n"
                               "    background-color: #221F2E; /* Цвет фона */\n"
                               "    border: none;\n"
                               "}\n"
                               "")
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(140, 20, 641, 521))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QWidget {\n"
                                      "    background-color: #2E2B3F; /* Цвет фона */\n"
                                      "    border: none;\n"
                                      "    border-radius: 5px;\n"
                                      "    color: #FFFFFF;\n"
                                      "}\n"
                                      "")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 30, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("     QPushButton {\n"
                                        "         background-color: #0090B3;\n"
                                        "         color: white;\n"
                                        "         border: none;\n"
                                        "         padding: 10px 20px;\n"
                                        "         border-radius: 5px;\n"
                                        "     }\n"
                                        "     QPushButton:hover {\n"
                                        "         background-color: #e67e22;\n"
                                        "     }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 80, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("     QPushButton {\n"
                                        "         background-color: #0090B3;\n"
                                        "         color: white;\n"
                                        "         border: none;\n"
                                        "         padding: 10px 20px;\n"
                                        "         border-radius: 5px;\n"
                                        "     }\n"
                                        "     QPushButton:hover {\n"
                                        "         background-color: #e67e22;\n"
                                        "     }")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setAutoFillBackground(False)
        self.tab_2.setStyleSheet("QWidget {\n"
                                 "    background-color: #221F2E; /* Цвет фона */\n"
                                 "    border: none; /* Убирает рамку у виджета внутри вкладки */\n"
                                 "    margin: 0; /* Убирает внешние отступы */\n"
                                 "    padding: 0; /* Убирает внутренние отступы */\n"
                                 "}")
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(140, 20, 641, 521))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QWidget {\n"
                                    "    background-color: #2E2B3F; /* Цвет фона */\n"
                                    "    border: none;\n"
                                    "    border-radius: 5px;\n"
                                    "    color: #FFFFFF;\n"
                                    "}\n"
                                    "")
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("     QPushButton {\n"
                                      "         background-color: #0090B3;\n"
                                      "         color: white;\n"
                                      "         border: none;\n"
                                      "         padding: 10px 20px;\n"
                                      "         border-radius: 5px;\n"
                                      "     }\n"
                                      "     QPushButton:hover {\n"
                                      "         background-color: #e67e22;\n"
                                      "     }")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 80, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("     QPushButton {\n"
                                        "         background-color: #0090B3;\n"
                                        "         color: white;\n"
                                        "         border: none;\n"
                                        "         padding: 10px 20px;\n"
                                        "         border-radius: 5px;\n"
                                        "     }\n"
                                        "     QPushButton:hover {\n"
                                        "         background-color: #e67e22;\n"
                                        "     }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.WinRAR = QtWidgets.QPushButton(self.groupBox)
        self.WinRAR.setGeometry(QtCore.QRect(10, 130, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.WinRAR.setFont(font)
        self.WinRAR.setStyleSheet("     QPushButton {\n"
                                  "         background-color: #0090B3;\n"
                                  "         color: white;\n"
                                  "         border: none;\n"
                                  "         padding: 10px 20px;\n"
                                  "         border-radius: 5px;\n"
                                  "     }\n"
                                  "     QPushButton:hover {\n"
                                  "         background-color: #e67e22;\n"
                                  "     }")
        self.WinRAR.setObjectName("WinRAR")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 180, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("     QPushButton {\n"
                                        "         background-color: #0090B3;\n"
                                        "         color: white;\n"
                                        "         border: none;\n"
                                        "         padding: 10px 20px;\n"
                                        "         border-radius: 5px;\n"
                                        "     }\n"
                                        "     QPushButton:hover {\n"
                                        "         background-color: #e67e22;\n"
                                        "     }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PHSV Helper"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Управление приложениями"))
        self.pushButton_3.setText(_translate("MainWindow", "Перезапустить ОПОРУ"))
        self.pushButton_5.setText(_translate("MainWindow", "Запустить ЖНВЛП"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Пользователи"))
        self.groupBox.setTitle(_translate("MainWindow", "Установка приложений"))
        self.pushButton.setText(_translate("MainWindow", "Установить ОПОРУ"))
        self.pushButton_2.setText(_translate("MainWindow", "Установить 7-Zip"))
        self.WinRAR.setText(_translate("MainWindow", "Установить WinRAR"))
        self.pushButton_4.setText(_translate("MainWindow", "Запустить активатор"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Администратор"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())